# Generated by Django 4.1.1 on 2022-10-06 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('stud_id', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('number', models.IntegerField()),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semister', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='IMAGE')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
